apiVersion: v1
kind: Pod
metadata:
  name: ms-dal-users
spec:
  containers:
  - name: ms-dal-users
    image: ms-dal-users:1.0-SNAPSHOT
    ports:
    - containerPort: 8081
    env:
    - name: project-port
      value: "8081"
    - name: project-jdbc-url
      value: "jdbc:mysql://localhost:3306/users?useSSL=false"
    - name: project-jdbc-username
      value: "root"
    - name: project-jdbc-password
      value: "my-secret-pw"
    - name: project-jdbc-dialect
      value: "org.hibernate.dialect.MySQL5InnoDBDialect"
    - name: project-jdbc-max-pool
      value: "5"